-- 코드를 입력하세요
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(B.PRICE * S.SALES) AS TOTAL_SALES
FROM AUTHOR A
INNER JOIN BOOK B
ON A.AUTHOR_ID = B.AUTHOR_ID
INNER JOIN (
    SELECT BOOK_ID, SUM(SALES) AS SALES
    FROM BOOK_SALES
    WHERE EXTRACT(YEAR_MONTH FROM SALES_DATE) = 202201
    GROUP BY BOOK_ID, EXTRACT(YEAR_MONTH FROM SALES_DATE)
) S
ON B.BOOK_ID = S.BOOK_ID
GROUP BY A.AUTHOR_NAME, B.CATEGORY
ORDER BY A.AUTHOR_ID ASC, B.CATEGORY DESC;