-- 코드를 입력하세요
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(B.PRICE * S.SALES) AS TOTAL_SALES
FROM AUTHOR A
INNER JOIN BOOK B
ON A.AUTHOR_ID = B.AUTHOR_ID
INNER JOIN BOOK_SALES S
ON B.BOOK_ID = S.BOOK_ID
WHERE EXTRACT(YEAR_MONTH FROM S.SALES_DATE) = 202201
GROUP BY A.AUTHOR_NAME, B.CATEGORY
ORDER BY A.AUTHOR_ID ASC, B.CATEGORY DESC;