-- 코드를 작성해주세요
SELECT D.ID
FROM (
        SELECT B.ID, B.PARENT_ID
        FROM ECOLI_DATA A
        INNER JOIN ECOLI_DATA B
        ON A.PARENT_ID IS NULL
        AND A.ID = B.PARENT_ID
     ) C
INNER JOIN ECOLI_DATA D
ON C.ID = D.PARENT_ID
