-- 코드를 입력하세요
WITH INTAKE_DURATION AS (
    SELECT ANIMAL_ID, RANK() OVER (ORDER BY DATEDIFF(O.DATETIME, I.DATETIME) DESC) AS RANKS
    FROM ANIMAL_OUTS O
    INNER JOIN ANIMAL_INS I
    USING (ANIMAL_ID)
    LIMIT 2
)

SELECT O.ANIMAL_ID, O.NAME
FROM ANIMAL_OUTS O
INNER JOIN INTAKE_DURATION D
USING (ANIMAL_ID)
ORDER BY D.RANKS ASC
