-- 코드를 입력하세요
SELECT YEAR(S.SALES_DATE) AS YEAR, MONTH(S.SALES_DATE) AS MONTH, U.GENDER, COUNT(DISTINCT S.USER_ID) AS USERS
FROM ONLINE_SALE S
INNER JOIN USER_INFO U
USING (USER_ID)
WHERE U.GENDER IS NOT NULL
GROUP BY YEAR(S.SALES_DATE), MONTH(S.SALES_DATE), U.GENDER
ORDER BY YEAR(S.SALES_DATE) ASC, MONTH(S.SALES_DATE) ASC, U.GENDER ASC;