-- 코드를 작성해주세요
WITH RECURSIVE GEN_DATA AS (
    SELECT A.ID, A.PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA A
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT B.ID, B.PARENT_ID, G.GENERATION + 1 AS GENERATION
    FROM ECOLI_DATA B
    INNER JOIN GEN_DATA G
    ON B.PARENT_ID = G.ID
)

SELECT COUNT(*) AS COUNT, GENERATION
FROM GEN_DATA G
LEFT JOIN ECOLI_DATA E
ON G.ID = E.PARENT_ID
WHERE E.ID IS NULL
GROUP BY GENERATION
ORDER BY GENERATION ASC;