-- 코드를 작성해주세요
WITH RECURSIVE GEN_DATA AS (
    SELECT A.ID, A.PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA A
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT B.ID, B.PARENT_ID, G.GENERATION + 1 AS GENERATION
    FROM ECOLI_DATA B
    INNER JOIN GEN_DATA G
    ON B.PARENT_ID = G.ID
)

SELECT COUNT(*) AS COUNT, GENERATION
FROM ECOLI_DATA E
INNER JOIN GEN_DATA G
USING (ID)
WHERE ID IN (SELECT ID 
             FROM ECOLI_DATA 
             WHERE ID NOT IN (SELECT PARENT_ID 
                              FROM ECOLI_DATA 
                              WHERE PARENT_ID IS NOT NULL))
GROUP BY GENERATION
ORDER BY GENERATION ASC;