-- 코드를 입력하세요
WITH 
TRUCK_DISCOUNT AS (
    SELECT
    MAX(IF(CAR_TYPE = '트럭' AND DURATION_TYPE = '7일 이상', DISCOUNT_RATE, 0)) AS SEVEN,
    MAX(IF(CAR_TYPE = '트럭' AND DURATION_TYPE = '30일 이상', DISCOUNT_RATE, 0)) AS THIRTY,
    MAX(IF(CAR_TYPE = '트럭' AND DURATION_TYPE = '90일 이상', DISCOUNT_RATE, 0)) AS NINETY
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
),
RENTAL_HISTORY AS (
    SELECT
        HISTORY_ID,
        CAR_ID,
        DAILY_FEE,
        DURATION,
        (
        CASE
        WHEN DURATION >= 90 THEN (1 - (NINETY / 100))
        WHEN DURATION >= 30 THEN (1 - (THIRTY / 100))
        WHEN DURATION >= 7 THEN (1 - (SEVEN / 100))
        ELSE 1.00
        END
        ) AS DISCOUNT_RATE
    FROM (
        SELECT HISTORY_ID, CAR_ID, DAILY_FEE, DATEDIFF(END_DATE, START_DATE) + 1 AS DURATION
        FROM CAR_RENTAL_COMPANY_CAR C
        INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
        USING (CAR_ID)
        WHERE CAR_TYPE = '트럭'
    ) AS H
    JOIN TRUCK_DISCOUNT
)

SELECT
    HISTORY_ID,
    ROUND(DURATION * DISCOUNT_RATE * DAILY_FEE) AS FEE
FROM RENTAL_HISTORY
JOIN TRUCK_DISCOUNT
ORDER BY FEE DESC, HISTORY_ID DESC;