-- 코드를 입력하세요
SELECT A.APNT_NO, P.PT_NAME, P.PT_NO, A.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM PATIENT P
INNER JOIN APPOINTMENT A
USING (PT_NO)
INNER JOIN DOCTOR D
ON A.MDDR_ID = D.DR_ID
WHERE DATE_FORMAT(APNT_YMD, '%Y%m%d') = '20220413'
AND APNT_CNCL_YN = 'N'
ORDER BY APNT_YMD ASC;