-- 코드를 입력하세요
SELECT U.USER_ID, U.NICKNAME, B.TOTAL_SALES
FROM USED_GOODS_USER U
INNER JOIN (
    SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
) B
ON B.WRITER_ID = U.USER_ID
WHERE TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES ASC;