-- 코드를 입력하세요
SELECT MONTH(A.START_DATE) AS MONTH, A.CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
INNER JOIN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN DATE('2022-08-01') AND DATE('2022-11-01')
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
) B
ON A.CAR_ID = B.CAR_ID
WHERE A.START_DATE BETWEEN DATE('2022-08-01') AND DATE('2022-11-01')
GROUP BY MONTH(A.START_DATE), A.CAR_ID
HAVING RECORDS > 0
ORDER BY MONTH ASC, A.CAR_ID DESC;