-- 코드를 작성해주세요
SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS D
INNER JOIN (
    SELECT SUM(CODE) AS CODE
    FROM SKILLCODES
    WHERE NAME IN ('Python', 'C#')
) S
WHERE D.SKILL_CODE & S.CODE != 0
ORDER BY ID ASC;