-- 코드를 작성해주세요
WITH YEAR_MAX AS (
    SELECT MAX(SIZE_OF_COLONY) AS MAX_SIZE, YEAR(DIFFERENTIATION_DATE) AS MAX_YEAR
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
)
SELECT Y.MAX_YEAR AS YEAR, Y.MAX_SIZE - E.SIZE_OF_COLONY AS YEAR_DEV, E.ID
FROM ECOLI_DATA E
INNER JOIN YEAR_MAX Y
ON YEAR(E.DIFFERENTIATION_DATE) = Y.MAX_YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC;