-- 코드를 작성해주세요
SELECT I.ID, N.FISH_NAME, I.LENGTH
FROM FISH_INFO I
INNER JOIN FISH_NAME_INFO N
ON I.FISH_TYPE = N.FISH_TYPE
INNER JOIN (
    SELECT I2.FISH_TYPE, MAX(I2.LENGTH) AS MAX_LENGTH
    FROM FISH_INFO I2
    GROUP BY I2.FISH_TYPE
) M
ON I.FISH_TYPE = M.FISH_TYPE AND I.LENGTH = M.MAX_LENGTH
ORDER BY I.ID ASC;