-- 코드를 입력하세요
SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM (
    SELECT CATEGORY, PRICE, PRODUCT_NAME, RANK() OVER (PARTITION BY CATEGORY ORDER BY PRICE DESC) AS RANKS
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
) A
WHERE RANKS = 1
ORDER BY MAX_PRICE DESC;